### ISSUE TITLE
data analysis? 

### ISSUE THREAD

**Issue by gedankenstuecke** [audy/berkeley-bowl-soups#1]
How much data did you already record? And did you do an analysis of the data yet? Just today I talked to colleagues about how predictable the selection is and I'd love to look into that :D

**Comment by audy** [comment]
The reason for creating this scraper was to generate data to build a predictive model for Berkeley Bowl soups. I've committed the `soups.sqlite` file which contains only 56 *unique* soup samples (there are often multiple samples per day).

**Comment by audy** [comment]
I haven't done any analysis. I think I have just enough data now where that might be a little bit interesting.

**Comment by gedankenstuecke** [comment]
Awesome, thanks. Btw: I also noticed that the `requirements.txt` is missing, if you could add it that would be great!

**Comment by gedankenstuecke** [comment]
Perfect, thanks! 👍
